version: 2.1

orbs:
  node: circleci/node@5.1.0

executors:
  docker:
    docker:
      - image: cimg/node:lts
  linux:
    machine:
      image: ubuntu-2004:2023.02.1
  macos:
    macos:
      xcode: 14.2.0

jobs:
  test-node:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run: npm ci
      - run: npm test
      - run: npm pack

workflows:
  simple:
    jobs:
      - test-node:
          matrix:
            parameters:
              os: [docker, linux, macos]
              node-version: ["19.8", "lts", "16.9", "14.21"]
